"use client";

import { useMemo, useState } from "react";
import { ArrowLeft, ChevronDown, ChevronLeft, ChevronRight, CirclePlay, Copy, ExternalLink, MoreHorizontal, Plus, Search, SlidersHorizontal } from "lucide-react";
import { Area, AreaChart, CartesianGrid, XAxis, YAxis } from "recharts";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { ChartContainer, ChartTooltip, ChartTooltipContent } from "@/components/ui/chart";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import type { Channel, ChannelStatus } from "./data";
import { MiniTrend, PageIntro, StatusBadge } from "./shared";

const views = ["All Channels", "Active", "Warm-up", "Warning", "Dead", "No Upload > 7 Days"];
const growth = [
  { day: "Aug 18", views: 156000 }, { day: "Aug 23", views: 181000 }, { day: "Aug 28", views: 174000 },
  { day: "Sep 02", views: 208000 }, { day: "Sep 07", views: 226000 }, { day: "Sep 12", views: 265000 }, { day: "Sep 16", views: 302000 },
];

export function ChannelsPage({ channels, onOpen, onAdd }: { channels: Channel[]; onOpen: (channel: Channel) => void; onAdd: () => void }) {
  const [query, setQuery] = useState(""); const [view, setView] = useState("All Channels"); const [status, setStatus] = useState("All statuses"); const [niche, setNiche] = useState("All niches"); const [selected, setSelected] = useState<string[]>([]);
  const filtered = useMemo(() => channels.filter((channel) => {
    const q = query.toLowerCase(); const queryMatch = channel.name.toLowerCase().includes(q) || channel.account.toLowerCase().includes(q) || channel.profile.toLowerCase().includes(q);
    const viewMatch = view === "All Channels" || (view === "No Upload > 7 Days" ? ["10 days ago", "24 days ago", "42 days ago", "No uploads"].includes(channel.lastUpload) : channel.status === view);
    return queryMatch && viewMatch && (status === "All statuses" || channel.status === status) && (niche === "All niches" || channel.niche === niche);
  }), [channels, query, view, status, niche]);
  const allSelected = filtered.length > 0 && filtered.every((c) => selected.includes(c.id));
  const selectAll = () => setSelected(allSelected ? selected.filter((id) => !filtered.some((c) => c.id === id)) : Array.from(new Set([...selected, ...filtered.map((c) => c.id)])));
  return <>
    <PageIntro title="Channels" description="Manage every channel, lifecycle stage and operational relationship from one place." action={<Button onClick={onAdd} className="rounded-lg bg-indigo-600 hover:bg-indigo-700"><Plus /> Add channel</Button>} />
    <div className="mb-4 flex gap-1 overflow-x-auto border-b border-slate-200 pb-px scrollbar-none">{views.map((item) => <button key={item} onClick={() => setView(item)} className={`relative shrink-0 px-3 py-2.5 text-sm font-medium ${view === item ? "text-indigo-700 after:absolute after:inset-x-2 after:bottom-[-1px] after:h-0.5 after:bg-indigo-600" : "text-slate-500 hover:text-slate-900"}`}>{item}</button>)}</div>
    <div className="sticky top-16 z-10 mb-3 flex flex-wrap items-center gap-2 rounded-xl border border-slate-200 bg-white p-3 shadow-sm">
      <div className="relative min-w-[220px] flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search channels, accounts, profiles..." className="h-9 w-full rounded-lg border border-slate-200 bg-slate-50 pl-9 pr-3 text-sm outline-none transition focus:border-indigo-300 focus:bg-white focus:ring-2 focus:ring-indigo-100" /></div>
      <Filter value={status} onChange={setStatus} options={["All statuses", "Active", "Warm-up", "Warning", "Paused", "Suspended", "Dead"]} />
      <Filter value={niche} onChange={setNiche} options={["All niches", "History", "Fishing", "Travel", "Ghibli", "Timelapse", "Defense", "Discovery"]} />
      <Button variant="outline" size="sm" className="h-9 rounded-lg"><SlidersHorizontal /> More filters</Button>
      {selected.length > 0 && <div className="flex items-center gap-2 border-l border-slate-200 pl-3"><span className="text-xs font-semibold text-indigo-600">{selected.length} selected</span><Button variant="outline" size="sm" onClick={() => toast.success("Bulk status update ready")}>Change status</Button><Button variant="outline" size="sm" onClick={() => toast.success("Owner assignment ready")}>Assign owner</Button></div>}
    </div>
    <div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-[0_1px_2px_rgb(15_23_42/0.03)]">
      <Table><TableHeader className="sticky top-[132px] z-[5] bg-slate-50"><TableRow className="hover:bg-slate-50"><TableHead className="w-10 pl-4"><Checkbox checked={allSelected} onCheckedChange={selectAll} aria-label="Select all" /></TableHead><TableHead>Channel</TableHead><TableHead>Status</TableHead><TableHead>Niche</TableHead><TableHead>Subscribers</TableHead><TableHead>Total views</TableHead><TableHead>Videos</TableHead><TableHead>Last upload</TableHead><TableHead>Account</TableHead><TableHead>Profile</TableHead><TableHead>Health</TableHead><TableHead>Owner</TableHead><TableHead className="w-10" /></TableRow></TableHeader>
        <TableBody>{filtered.map((channel) => <TableRow key={channel.id} data-state={selected.includes(channel.id) ? "selected" : undefined} className="cursor-pointer hover:bg-slate-50"><TableCell className="pl-4" onClick={(e) => e.stopPropagation()}><Checkbox checked={selected.includes(channel.id)} onCheckedChange={() => setSelected((current) => current.includes(channel.id) ? current.filter((id) => id !== channel.id) : [...current, channel.id])} aria-label={`Select ${channel.name}`} /></TableCell><TableCell onClick={() => onOpen(channel)}><div className="flex items-center gap-3"><ChannelAvatar name={channel.name} /><div><p className="font-semibold text-slate-900">{channel.name}</p><p className="text-xs text-slate-400">{channel.handle}</p></div></div></TableCell><TableCell onClick={() => onOpen(channel)}><StatusBadge status={channel.status} /></TableCell><TableCell onClick={() => onOpen(channel)} className="text-slate-600">{channel.niche}</TableCell><TableCell onClick={() => onOpen(channel)} className="font-medium text-slate-800">{channel.subscribers}</TableCell><TableCell onClick={() => onOpen(channel)} className="text-slate-600">{channel.views}</TableCell><TableCell onClick={() => onOpen(channel)} className="text-slate-600">{channel.videos}</TableCell><TableCell onClick={() => onOpen(channel)} className="text-slate-600">{channel.lastUpload}</TableCell><TableCell onClick={() => onOpen(channel)} className="max-w-44 truncate text-slate-500">{channel.account}</TableCell><TableCell onClick={() => onOpen(channel)} className="text-slate-600">{channel.profile}</TableCell><TableCell onClick={() => onOpen(channel)}><StatusBadge status={channel.health} /></TableCell><TableCell onClick={() => onOpen(channel)}><div className="flex items-center gap-2"><span className="grid size-6 place-items-center rounded-full bg-slate-200 text-[10px] font-bold text-slate-600">{channel.owner[0]}</span>{channel.owner}</div></TableCell><TableCell><Button variant="ghost" size="icon-sm" aria-label="Channel actions"><MoreHorizontal /></Button></TableCell></TableRow>)}{filtered.length === 0 && <TableRow><TableCell colSpan={13} className="h-48 text-center"><p className="font-medium text-slate-700">No channels found</p><p className="mt-1 text-sm text-slate-400">Try adjusting your search or filters.</p></TableCell></TableRow>}</TableBody>
      </Table><div className="flex flex-col gap-3 border-t border-slate-200 px-4 py-3 text-sm text-slate-500 sm:flex-row sm:items-center"><span className="flex-1">Showing {filtered.length} of {channels.length} channels</span><div className="flex items-center gap-1"><Button variant="outline" size="icon-sm" disabled><ChevronLeft /></Button><Button variant="outline" size="sm" className="bg-slate-900 text-white">1</Button><Button variant="ghost" size="sm">2</Button><Button variant="ghost" size="sm">3</Button><Button variant="outline" size="icon-sm"><ChevronRight /></Button></div></div>
    </div>
  </>;
}

function Filter({ value, onChange, options }: { value: string; onChange: (value: string) => void; options: string[] }) {
  return <label className="relative"><select value={value} onChange={(e) => onChange(e.target.value)} className="h-9 appearance-none rounded-lg border border-slate-200 bg-white pl-3 pr-8 text-sm text-slate-600 outline-none hover:bg-slate-50 focus:border-indigo-300">{options.map((option) => <option key={option}>{option}</option>)}</select><ChevronDown className="pointer-events-none absolute right-2.5 top-1/2 size-3.5 -translate-y-1/2 text-slate-400" /></label>;
}

function ChannelAvatar({ name, large = false }: { name: string; large?: boolean }) {
  const colors = ["bg-indigo-100 text-indigo-700", "bg-sky-100 text-sky-700", "bg-emerald-100 text-emerald-700", "bg-amber-100 text-amber-700"];
  const color = colors[name.length % colors.length];
  return <span className={`grid shrink-0 place-items-center rounded-xl font-bold ${color} ${large ? "size-16 text-xl" : "size-9 text-xs"}`}>{name.split(" ").map((word) => word[0]).slice(0, 2).join("")}</span>;
}

export function ChannelDetail({ channel, onBack, onEdit }: { channel: Channel; onBack: () => void; onEdit: () => void }) {
  return <div>
    <button onClick={onBack} className="mb-5 flex items-center gap-2 text-sm font-medium text-slate-500 hover:text-slate-900"><ArrowLeft className="size-4" /> Back to channels</button>
    <div className="mb-6 flex flex-col gap-5 rounded-xl border border-slate-200 bg-white p-5 sm:flex-row sm:items-center"><ChannelAvatar name={channel.name} large /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-2xl font-semibold tracking-[-0.03em] text-slate-950">{channel.name}</h2><StatusBadge status={channel.status} /></div><p className="mt-1 text-sm text-slate-500">{channel.handle} · {channel.niche} · {channel.country}</p></div><div className="flex flex-wrap gap-2"><Button variant="outline"><CirclePlay /> Open YouTube</Button><Button variant="outline"><ExternalLink /> YouTube Studio</Button><Button onClick={onEdit} className="bg-indigo-600 hover:bg-indigo-700">Edit channel</Button></div></div>
    <div className="mb-5 grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-6">{[["Subscribers", channel.subscribers], ["Total views", channel.views], ["Videos", String(channel.videos)], ["Average views", channel.avgViews], ["Last upload", channel.lastUpload], ["Growth 30 days", channel.growth]].map(([label, value]) => <div key={label} className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs font-medium text-slate-500">{label}</p><div className="mt-2 flex items-center gap-2"><p className="text-lg font-semibold text-slate-900">{value}</p>{label === "Growth 30 days" && <MiniTrend value={value} />}</div></div>)}</div>
    <Tabs defaultValue="overview" className="gap-4"><TabsList variant="line" className="w-full justify-start overflow-x-auto border-b border-slate-200 pb-1 scrollbar-none">{["Overview", "Account", "Content", "Analytics", "Notes", "Activity"].map((tab) => <TabsTrigger key={tab} value={tab.toLowerCase()} className="flex-none px-3">{tab}</TabsTrigger>)}</TabsList>
      <TabsContent value="overview"><div className="grid gap-4 xl:grid-cols-[0.8fr_1.2fr]"><InfoPanel title="Channel information" rows={[["Status", channel.status], ["Niche", channel.niche], ["Owner", channel.owner], ["Country", channel.country], ["Purchased", channel.purchased], ["Started", channel.started], ["Profile", channel.profile], ["Reference", "Historia Civilis"]]} /><div className="rounded-xl border border-slate-200 bg-white p-5"><h3 className="font-semibold text-slate-900">Views growth</h3><p className="mt-1 text-sm text-slate-500">Daily views over the last 30 days</p><ChartContainer config={{ views: { label: "Views", color: "#4f46e5" } }} className="mt-5 h-[280px] w-full aspect-auto"><AreaChart data={growth}><defs><linearGradient id="detailgrowth" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#4f46e5" stopOpacity={0.16}/><stop offset="100%" stopColor="#4f46e5" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#eef2f7" /><XAxis dataKey="day" axisLine={false} tickLine={false} /><YAxis hide /><ChartTooltip content={<ChartTooltipContent />} /><Area type="monotone" dataKey="views" stroke="#4f46e5" strokeWidth={2.5} fill="url(#detailgrowth)" /></AreaChart></ChartContainer></div></div></TabsContent>
      <TabsContent value="account"><div className="grid gap-4 lg:grid-cols-2"><InfoPanel title="Linked account" rows={[["Email", channel.account], ["Recovery email", "recovery.•••@outlook.com"], ["Phone", "+1 ••• ••• 2291"], ["2FA enabled", "Yes"], ["Account source", "Private vendor"], ["Country", channel.country]]} copy /><div className="rounded-xl border border-amber-200 bg-amber-50 p-5"><h3 className="font-semibold text-amber-900">Credential security</h3><p className="mt-2 text-sm leading-6 text-amber-800">Passwords and 2FA secrets are never shown here. This workspace is prepared for a future encrypted vault integration with role-based access and audit logging.</p></div></div></TabsContent>
      <TabsContent value="content"><VideoTable /></TabsContent>
      <TabsContent value="analytics"><div className="grid gap-4 md:grid-cols-3">{["Subscriber growth", "Views growth", "Upload frequency"].map((name, index) => <div key={name} className="rounded-xl border border-slate-200 bg-white p-5"><p className="text-sm font-medium text-slate-500">{name}</p><p className="mt-2 text-2xl font-semibold text-slate-900">{["+8.4K", "+1.2M", "2.4 / week"][index]}</p><MiniTrend value={["+12.8%", "+18.4%", "+4.2%"][index]} /></div>)}</div></TabsContent>
      <TabsContent value="notes"><div className="rounded-xl border border-slate-200 bg-white p-5"><div className="mb-4 flex items-center justify-between"><h3 className="font-semibold">Notes</h3><Button size="sm" onClick={() => toast.success("Note added")}>Add note</Button></div><div className="space-y-3"><Note text="Focus on long-form Roman history; recent naval content performs above baseline." date="Sep 14" pinned /><Note text="Thumbnail style A/B test: illustrated map vs. historical portrait." date="Sep 08" /></div></div></TabsContent>
      <TabsContent value="activity"><div className="rounded-xl border border-slate-200 bg-white p-5"><h3 className="mb-5 font-semibold">Activity timeline</h3>{["Status changed: Warm-up → Active", "Profile-023 linked", "Niche changed to History", "Channel created"].map((item, index) => <div key={item} className="relative flex gap-4 pb-6 last:pb-0"><span className="relative z-10 mt-1 size-2.5 rounded-full bg-indigo-500 ring-4 ring-indigo-50" /><span className="absolute bottom-0 left-[4px] top-3 w-px bg-slate-200 last:hidden" /><div><p className="text-sm font-medium text-slate-800">{item}</p><p className="mt-1 text-xs text-slate-400">{["10 minutes ago", "2 days ago", "May 16, 2026", "April 02, 2025"][index]} · Monz</p></div></div>)}</div></TabsContent>
    </Tabs>
  </div>;
}

function InfoPanel({ title, rows, copy }: { title: string; rows: string[][]; copy?: boolean }) {
  return <div className="rounded-xl border border-slate-200 bg-white p-5"><h3 className="mb-4 font-semibold text-slate-900">{title}</h3><dl className="divide-y divide-slate-100">{rows.map(([label, value]) => <div key={label} className="grid grid-cols-[130px_1fr_auto] items-center gap-3 py-3 text-sm"><dt className="text-slate-500">{label}</dt><dd className="font-medium text-slate-800">{value}</dd>{copy && <button onClick={() => { navigator.clipboard?.writeText(value); toast.success(`${label} copied`); }} className="text-slate-400 hover:text-indigo-600"><Copy className="size-4" /></button>}</div>)}</dl></div>;
}
function VideoTable() {
  const videos = [["How Ancient Rome Really Worked", "Sep 15, 2026", "482K", "18K", "1.2K", "18:24", "Top 10%"], ["The Empire That Vanished", "Sep 08, 2026", "261K", "12K", "684", "22:08", "Above avg."], ["Why Sparta Actually Fell", "Aug 30, 2026", "198K", "9.4K", "511", "16:42", "Average"]];
  return <div className="overflow-hidden rounded-xl border border-slate-200 bg-white"><Table><TableHeader className="bg-slate-50"><TableRow><TableHead>Video</TableHead><TableHead>Published</TableHead><TableHead>Views</TableHead><TableHead>Likes</TableHead><TableHead>Comments</TableHead><TableHead>Duration</TableHead><TableHead>Performance</TableHead></TableRow></TableHeader><TableBody>{videos.map((row) => <TableRow key={row[0]}>{row.map((cell, i) => <TableCell key={cell} className={i === 0 ? "font-semibold text-slate-900" : "text-slate-600"}>{i === 0 && <span className="mr-3 inline-block h-10 w-16 rounded-md bg-gradient-to-br from-slate-700 to-slate-950 align-middle" />}{cell}</TableCell>)}</TableRow>)}</TableBody></Table></div>;
}
function Note({ text, date, pinned }: { text: string; date: string; pinned?: boolean }) { return <div className="rounded-lg border border-slate-200 p-4"><div className="flex gap-3"><p className="flex-1 text-sm leading-6 text-slate-700">{text}</p>{pinned && <span className="h-fit rounded-full bg-indigo-50 px-2 py-1 text-xs font-medium text-indigo-600">Pinned</span>}</div><p className="mt-2 text-xs text-slate-400">Monz · {date}</p></div>; }
